FROM node:18-alpine AS builder
WORKDIR /app

COPY server/package*.json ./
RUN npm ci --omit=dev

FROM node:18-alpine
WORKDIR /app
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder /app/node_modules ./node_modules
COPY server/ ./

RUN chown -R appuser:appgroup /app
USER appuser

EXPOSE 5000
CMD ["node", "server.js"]
